### ISSUE TITLE
mpirun command error

### ISSUE THREAD

**Issue by yu-ting-py** [Trel725/plasmon-meep#7]
I try to use `mpirun ` command to run the meep script, but it shows:

```
Starting reference run
-----------
Initializing structure...
Starting reference run
-----------
Initializing structure...
time for choose_chunkdivision = 0.000712872 s
Working in 2D dimensions.
Computational cell is 2.9 x 2.9 x 0 with resolution 250
time for choose_chunkdivision = 0.000846863 s
Working in 2D dimensions.
Computational cell is 2.9 x 2.9 x 0 with resolution 250
time for set_epsilon = 0.708489 s
-----------
time for set_epsilon = 0.708814 s
-----------
creating output file "./data-ref.h5"...
creating output file "./data-ref.h5"...
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 140286224963392:
  #000: H5F.c line 444 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1567 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #002: H5FD.c line 1640 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #003: H5FDsec2.c line 959 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
Traceback (most recent call last):
  File "./fdtd_yt.py", line 77, in <module>
    until_after_sources=mp.stop_when_fields_decayed(10, comp, pt, 1e-2))
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 3628, in run
    self._run_sources_until(until_after_sources, step_funcs)
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 2213, in _run_sources_until
    self._run_until(new_conds, step_funcs)
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 2176, in _run_until
    _eval_step_func(self, func, 'step')
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 4014, in _eval_step_func
    func(sim, todo)
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 4202, in _to_appended
    _eval_step_func(sim, func, todo)
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 4014, in _eval_step_func
    func(sim, todo)
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 4102, in _every
    _eval_step_func(sim, func, todo)
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 4012, in _eval_step_func
    func(sim)
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 4636, in output_efield_x
    sim.output_component(mp.Ex)
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/simulation.py", line 3067, in output_component
    self.fields.output_hdf5(c, vol, h5, append, self.output_single_precision,self.get_filename_prefix(), frequency)
  File "/home/tim/anaconda3/envs/mpn/lib/python3.7/site-packages/meep/__init__.py", line 3912, in output_hdf5
    return _meep.fields_output_hdf5(self, *args)
RuntimeError: meep: error on line 458 of h5file.cpp: error opening HDF5 output file
```

How to fix this problem?

**Comment by Trel725** [comment]
Looks like problems with installation, please refer to the meep documentation. Also you may have a look [here](https://meep.readthedocs.io/en/latest/Build_From_Source/#hdf5).
